# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 13:32
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='\u042d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u0430\u044f \u043f\u043e\u0447\u0442\u0430')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='\u0418\u043c\u044f')),
                ('gravatar', models.URLField(blank=True, null=True, verbose_name='Gravatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u0435\u043d')),
                ('is_admin', models.BooleanField(default=False, verbose_name='\u0410\u0434\u043c\u0438\u043d')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('language', models.CharField(blank=True, choices=[('RU', '\u0420\u0443\u0441\u0441\u043a\u0438\u0439'), ('EN', '\u0410\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u0438\u0439')], default='RU', max_length=2, null=True, verbose_name='Language')),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Moscow', verbose_name='Timezone')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c',
                'verbose_name_plural': '\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0438',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0430\u043a\u043a\u0430\u0443\u043d\u0442\u0430')),
                ('shortname', models.CharField(max_length=4, verbose_name='4-\u0445 \u0437\u043d\u0430\u0447\u043d\u043e\u0435 \u043e\u0431\u043e\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('google_tracing', models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Universal Analytics ID')),
                ('added', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('updated', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u043e\u0441\u043b\u0435\u0434\u043d\u0435\u0433\u043e \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f')),
                ('is_trial', models.BooleanField(default=False, verbose_name='\u041a\u043e\u043c\u043f\u0430\u043d\u0438\u044f \u043d\u0430 \u0442\u0440\u0438\u0430\u043b\u0435')),
                ('trial_expires', models.DateField(blank=True, null=True)),
                ('index_num', models.PositiveIntegerField(default=1, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0438\u043d\u0434\u0435\u043a\u0441\u0430')),
                ('language', models.CharField(choices=[('RU', '\u0420\u0443\u0441\u0441\u043a\u0438\u0439'), ('EN', '\u0410\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u0438\u0439')], default='RU', max_length=2, verbose_name='Language')),
            ],
            options={
                'verbose_name': '\u0410\u043a\u043a\u0430\u0443\u043d\u0442',
                'verbose_name_plural': '\u0410\u043a\u043a\u0430\u0443\u043d\u0442\u044b',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.Account', verbose_name='\u0421\u0432\u044f\u0437\u0430\u043d\u043d\u044b\u0439 \u0430\u043a\u043a\u0430\u0443\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
