# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20170112_1338'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='test_app_user',
        ),
    ]
